#mapping values xml->openehr
vmapping_xml_openehr={ \
'Dataelement_85_1':{
    'female':'FEMALE',
    'male':'MALE',
    'other':'OTHER'},
'Dataelement_92_1':{
    'Localization of primary tumor - C18.0':'C 18.0 - Caecum',
    'Localization of primary tumor - C18.1':'C 18.1 - Appendix',
    'Localization of primary tumor - C18.2':'C 18.2 - Ascending colon',
    'Localization of primary tumor - C18.3':'C 18.3 - Hepatic flexure',
    'Localization of primary tumor - C18.4':'C 18.4 - Transverse colon',
    'Localization of primary tumor - C18.5':'C 18.5 - Splenic flexure',
    'Localization of primary tumor - C18.6':'C 18.6 - Descending colon',
    'Localization of primary tumor - C18.7':'C 18.7 - Sigmoid colon',
    'Localization of primary tumor - C19':'C 19 - Rectosigmoid junction',
    'Localization of primary tumor - C20':'C 20 - Rectum'},
'Dataelement_91_1':{
    'Adenocarcinoma':'Adenocarcinoma',
    'High-grade neuroendocrine carcinoma':'High-grade neuroendocrine carcinoma',
    'Medullary carcinoma':'Medullary carcinoma',
    'Mixed adenoneuroendocrine carcinoma':'Mixed adenoneuroendocrine carcinoma',
    'Mucinous carcinoma':'Mucinous adenocarcinoma',
    'Other':'Other',
    'Signet-ring cell carcinoma':'Signet ring cell carcinoma',
    'Signet ring cell carcinoma':'Signet ring cell carcinoma',
    'Undifferentiated carcinoma':'Undifferentiated carcinoma',
    'Large cell neuroendocrine carcinoma':'Large cell neuroendocrine carcinoma',
    'small cell neuroendocrine carcinoma':'Small cell neuroendocrine carcinoma',
    'Squamous cell carcinoma':'Squamous cell carcinoma',
    'Adeonsquamous carcinoma':'Adenosquamous carcinoma',
    'Serrated adenocarcinoma':'Serrated adenocarcinoma'},
'Dataelement_71_1':{
    'Primary Tumor - T0':'T0',   
    'Primary Tumor - T1':'T1',   
    'Primary Tumor - T2':'T2',   
    'Primary Tumor - T3':'T3',   
    'Primary Tumor - T4a':'T4a',   
    'Primary Tumor - T4b':'T4b',   
    'Primary Tumor - T4':'T4',   
    'Primary Tumor - Tis':'Tis',   
    'Primary Tumor - TX':'TX'},
'Dataelement_77_1':{
    'Regional lymph nodes - N0':'N0',
    'Regional lymph nodes - N1a':'N1a',
    'Regional lymph nodes - N1b':'N1b',
    'Regional lymph nodes - N1c':'N1c',
    'Regional lymph nodes - N1':'N1',
    'Regional lymph nodes - N2a':'N2a',
    'Regional lymph nodes - N2b':'N2b',
    'Regional lymph nodes - N2':'N2',
    'Regional lymph nodes - N3':'N3',
    'Regional lymph nodes - NX':'NX'},
'Dataelement_75_1':{
    'Distant metastasis - M0':'M0',
    'Distant metastasis - M1a':'M1a',
    'Distant metastasis - M1b':'M1b',
    'Distant metastasis - M1c':'M1c',
    'Distant metastasis - M1':'M1',
    'Distant metastasis - MX':'MX'},
'Dataelement_83_1':{
    'WHO Grading - Grade - G1':'G1',
    'WHO Grading - Grade - G2':'G2',
    'WHO Grading - Grade - G3':'G3',
    'WHO Grading - Grade - G4':'G4',
    'WHO Grading - Grade - GX':'GX'},
'Dataelement_70_2':{
    'Stage - 0':'Stage - 0',
    'Stage - I':'Stage - I',
    'Stage - II A':'Stage - II A',
    'Stage - IIB':'Stage - IIB',
    'Stage - IIC':'Stage - IIC',
    'Stage - II':'Stage - II',
    'Stage - IIIA':'Stage - IIIA',
    'Stage - IIIB':'Stage - IIIB',
    'Stage - IIIC':'Stage - IIIC',
    'Stage - III':'Stage - III',
    'Stage - IVA':'Stage - IVA',
    'Stage - IVB':'Stage - IVB',
    'Stage - IVC':'Stage - IVC',
    'Stage - IV':'Stage - IV'},
'Dataelement_68_2':{
    'Localization of metastasis - Adrenals':'Adrenals',
    'Localization of metastasis - Bone marrow':'Bone marrow',
    'Localization of metastasis - Brain':'Brain',
    'Localization of metastasis - Hepatic':'Hepatic',
    'Localization of metastasis - Lymph nodes':'Lymph Nodes',
    'Localization of metastasis - None':'None',
    'Localization of metastasis - Osseous':'Osseous',
    'Localization of metastasis - Others':'Others',
    'Localization of metastasis - Peritoneum':'Peritoneum',
    'Localization of metastasis - Pleura':'Pleura',
    'Localization of metastasis - Pulmonary':'Lung',
    'Localization of metastasis - Skin':'Skin'},
'Dataelement_54_2':{   
                'Healthy colon tissue':'Tissue specimen from colon',
                'Other':'Other specimen type',
                'Tumor':'Tumor tissue sample'},
'Dataelement_55_2':{
    'Cryopreservation':'Cryopreservation',
    'FFPE':'FFPE',
    'Other':'Other'},
'Dataelement_49_1':{
    'Abdomino-perineal resection':'Abdomino-perineal resection',
    'Anterior resection of rectum':'Anterior resection of rectum',
    'Endo-rectal tumor resection':'Endo-rectal tumor resection',
    'Left hemicolectomy':'Left hemicolectomy',
    'Low anteroir colon resection':'Low anterior colon resection',
    'Other':'Other',
    'Pan-procto colectomy':'Pan-procto colectomy',
    'Right hemicolectomy':'Right hemicolectomy',
    'Sigmoid colectomy':'Sigmoid colectomy',
    'Total colectomy':'Total colectomy',
    'Transverse colectomy':'Transverse colectomy'},
'Dataelement_93_1':{
    'Location of tumor - C18.0':'C 18.0 - Caecum',
    'Location of tumor - C18.1':'C 18.1 - Appendix',
    'Location of tumor - C18.2':'C 18.2 - Ascending colon',
    'Location of tumor - C18.3':'C 18.3 - Hepatic flexure',
    'Location of tumor - C18.4':'C 18.4 - Transverse colon',
    'Location of tumor - C18.5':'C 18.5 - Splenic flexure',
    'Location of tumor - C18.6':'C 18.6 - Descending colon',
    'Location of tumor - C18.7':'C 18.7 - Sigmoid colon',
    'Location of tumor - C19.9':'C 19 - Rectosigmoid junction',
    'Location of tumor - C19':'C 19 - Rectosigmoid junction',
    'Location of tumor - C20.9':'C 20 - Rectum',
    'Location of tumor - C20':'C 20 - Rectum'},
'Dataelement_9_2':{
    'R0':'R0',
    'R1':'R1',
    'R2':'R2',
    'RX':'RX'},
'Dataelement_33_1':{
    'Specific response - Complete response':'Complete response',
    'Specific response - Partial response':'Partial response',
    'Specific response - Progressive disease':'Progressive disease',
    'Specific response - Stable disease':'Stable disease'},
'Dataelement_25_3':{
    'Mutated':'Present',
    'Not done':'Indeterminate',
    'Not mutated':'Absent'},
'Dataelement_24_4':{
    'Mutated':'Present',
    'Not done':'Indeterminate',
    'Not mutated':'Absent'},
'Dataelement_23_5':{
    'Mutated':'Present',
    'Not done':'Indeterminate',
    'Not mutated':'Absent'},
'Dataelement_22_4':{
    'Mutated':'Present',
    'Not done':'Indeterminate',
    'Not mutated':'Absent'},
'Dataelement_21_5':{
    'Mutated':'Present',
    'Not done':'Indeterminate',
    'Not mutated':'Absent'},
'Dataelement_20_3':{
    'Mutated':'Present',
    'Not done':'Indeterminate',
    'Not mutated':'Absent'},
'Dataelement_2_2':{
    'False':'FALSE',
    'True':'TRUE'},
'Dataelement_57_3':{
    'Can be generated':'Can be generated',
    'No':'No',
    'Readily available':'Readily available'},
'Dataelement_58_2':{
    'Can be generated':'Can be generated',
    'Invasion front not included':'Invasion front not included',
    'No':'No',
    'Readily available':'Readily available'}, 
'Dataelement_73_3':{
    '4th edition or earlier':'4th. ed (used before 1998)',
    '5th edition':'5th. ed (used 1998-2002)',
    '6th edition':'6th. ed (used 2003-2009)',
    '7th edition':'7th ed. (used 2010- 2017)',
    '8th edition':'8th ed. (used since 2017)',
    'Not known':'Not known'},
'Dataelement_53_3':{
    '2nd edition':'2nd ed. (1991- 2000)',
    '3rd edition':'3rd ed. (2001-2010)',
    '4th edition':'4th ed. (used since 2011)',
    'Not known':'Edition not known'},
'Dataelement_59_5':{
    'Other':'Other',
    'Scheme of pharmacotherapy - 5-FU 225 mg/m2 i.v. continuous infusion, 5 days per week':'5-FU 225 mg/m2 i.v. continuous infusion, 5 days per week',
    'Scheme of pharmacotherapy - 5-FU 400 mg/m2 + 100 mg i.v. bolus, d 1,2, 11,12,21,22':'5-FU 400 mg/m2 + 100 mg i.v. bolus, d 1,2, 11,12,21,22',
    'Scheme of pharmacotherapy - Capecitabine 800-825 mg/m2 bid po, day 1-5, together with radiation or continuously untill end of radiation':'Capecitabine 800-825 mg/m2 bid po, day 1-5, together with radiation or continuously untill end of radiation',
    'Scheme of pharmacotherapy - UFT (300-340mg/m2/day) and LV (22.5-90 mg/day) po continuously, 5(-7) days per week, together with radiotherapy':'UFT (300-340mg/m2/day) and LV (22.5-90 mg/day) po continuously, 5(-7) days per week, together with radiotherapy'},
'Dataelement_31_3':{
    'CT - Done, data available':'Done, data available',
    'CT - Done, data not available':'Done, data not available',
    'CT- Not done':'Not done',
    'CT - Unknown':'Unknown'},
'Dataelement_61_5':{
    'Liver imaging - Done, data available':'Done, data available',
    'Liver imaging - Done, data not available':'Done, data not available',
    'Liver imaging - Unknown':'Unknown',
    'Liver imaging - Unknown Not done':'Not done'},
'Dataelement_88_1':{
    'Colonoscopy diagnostic exam - Negative':'Negative',
    'Colonoscopy diagnostic exam- Not done':'Not done',
    'Colonoscopy diagnostic exam - Positive':'Positive',
    'Colonoscopy diagnostic exam- Unknown':'Unknown'},
'Dataelement_63_4':{
    'Lung imaging - Done, data available':'Done, data available',
    'Lung imaging - Done, data not available':'Done, data not available',
    'Lung imaging - Not done':'Not done',
    'Lung imaging - Unknown':'Unknown'},
'Dataelement_30_3':{
    'MRI - Done, data available':'Done, data available',
    'MRI - Done, data not available':'Done, data not available',
    'MRI - Not done':'Not done',
    'MRI - Unknown':'Unknown'},
'Dataelement_87_1':{
    'BRAF, PIC3CA, HER2 mutation status - mutated':'Mutated',
    'BRAF, PIC3CA, HER2 mutation status - not done':'Not done',
    'BRAF, PIC3CA, HER2 mutation status - not mutated':'Not mutated',
    'BRAF, PIC3CA, HER2 mutation status - Partial information available':'Partial information available'},
'Dataelement_14_3':{
    'NO':'No',
    'NOT_DONE':'Not done',
    'YES':'Yes'},
'Dataelement_15_2':{
    'EXPRESSION':'Expression',
    'LOSS_OF_EXPRESSION':'Loss of expression',
    'NOT_DONE':'Not done'},
'Dataelement_16_3':{
    'False':'FALSE',
    'True':'TRUE'},
'Dataelement_5_2':{
    'ALIVE':'person is still alive',
    'DEATH_COLON_CANCER':'death due to colon cancer',
    'DEATH_OTHER':'death due to other reasons',
    'DEATH_UNKNOWN_REASON':'death for unknown reasons',
    'UNKNOWN':'unknown'}
}